---
- name: Deploy the db on the server
  hosts: all
  remote_user: azureuser
  tasks:
    - name: Copy the sources
      synchronize:
        src: ./
        dest: /home/azureuser/db
        delete: yes

    - name: Stop database services
      shell:
        docker-compose down
      args:
        chdir:
          /home/azureuser/db

    - name: Build database services
      shell:
        docker-compose build test_db
      args:
        chdir:
          /home/azureuser/app/database

    - name: Start database services
      shell:
        docker-compose up --detach test_db
      args:
        chdir:
          /home/azureuser/db
