version: "3.3"
services:
  backend:
    build: app/backend
    ports:
      - "3001:3001"
      - "8080:8080"
    restart: always
    volumes:
      - file-storage:/storage
  frontend:
    build: app/frontend
    ports:
      - "3000:3000"
    restart: always
  nginx:
    build: app/nginx
    ports:
      - "80:80"
    restart: always
  main_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'mysqluser'
      MYSQL_PASSWORD: 'attic-humorous-stylishly'
      MYSQL_ROOT_PASSWORD: 'attic-humorous-stylishly'
    ports:
      - '3307:3307'
    expose:
      - '3307'
    volumes:
      - main-db:/var/lib/mysql

volumes:
  main-db:
  file-storage:
