apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: main-db
  name: main_db
spec:
  ports:
    - name: "3307"
      port: 3307
      targetPort: 3307
    - name: 3307-tcp
      port: 3307
      targetPort: 3307
  selector:
    io.kompose.service: main-db
status:
  loadBalancer: {}
