version: "3.3"
services:
  backend:
    build: backend
    ports:
      - "3001:3001"
      - "8080:8080"
    restart: always
    volumes:
      - file-storage:/storage
  frontend:
    build: frontend
    ports:
      - "3000:3000"
    restart: always
  nginx:
    build: nginx
    ports:
      - "80:80"
    restart: always

volumes:
  file-storage:
